// Generated by gencpp from file delivery_robot_serial_handler/Pos.msg
// DO NOT EDIT!


#ifndef DELIVERY_ROBOT_SERIAL_HANDLER_MESSAGE_POS_H
#define DELIVERY_ROBOT_SERIAL_HANDLER_MESSAGE_POS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delivery_robot_serial_handler
{
template <class ContainerAllocator>
struct Pos_
{
  typedef Pos_<ContainerAllocator> Type;

  Pos_()
    : P1(0)
    , P2(0)  {
    }
  Pos_(const ContainerAllocator& _alloc)
    : P1(0)
    , P2(0)  {
  (void)_alloc;
    }



   typedef int32_t _P1_type;
  _P1_type P1;

   typedef int32_t _P2_type;
  _P2_type P2;





  typedef boost::shared_ptr< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> const> ConstPtr;

}; // struct Pos_

typedef ::delivery_robot_serial_handler::Pos_<std::allocator<void> > Pos;

typedef boost::shared_ptr< ::delivery_robot_serial_handler::Pos > PosPtr;
typedef boost::shared_ptr< ::delivery_robot_serial_handler::Pos const> PosConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delivery_robot_serial_handler::Pos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::delivery_robot_serial_handler::Pos_<ContainerAllocator1> & lhs, const ::delivery_robot_serial_handler::Pos_<ContainerAllocator2> & rhs)
{
  return lhs.P1 == rhs.P1 &&
    lhs.P2 == rhs.P2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::delivery_robot_serial_handler::Pos_<ContainerAllocator1> & lhs, const ::delivery_robot_serial_handler::Pos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace delivery_robot_serial_handler

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3362efe2d7e58f1252e89f624acd8c9f";
  }

  static const char* value(const ::delivery_robot_serial_handler::Pos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3362efe2d7e58f12ULL;
  static const uint64_t static_value2 = 0x52e89f624acd8c9fULL;
};

template<class ContainerAllocator>
struct DataType< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delivery_robot_serial_handler/Pos";
  }

  static const char* value(const ::delivery_robot_serial_handler::Pos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 P1\n"
"int32 P2\n"
;
  }

  static const char* value(const ::delivery_robot_serial_handler::Pos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.P1);
      stream.next(m.P2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delivery_robot_serial_handler::Pos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delivery_robot_serial_handler::Pos_<ContainerAllocator>& v)
  {
    s << indent << "P1: ";
    Printer<int32_t>::stream(s, indent + "  ", v.P1);
    s << indent << "P2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.P2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELIVERY_ROBOT_SERIAL_HANDLER_MESSAGE_POS_H
